import { describe, it, expect } from "vitest";
import {
  rawObjectKey,
  eraseRawByHash,
  RawMetadataMissingError,
  HASH_SHARD_LEN,
} from "../src/raw";
import type { Env, Impression } from "../src/types";

/**
 * NOTE: fixture identifiers are deliberately descriptive rather than
 * random-looking strings, so they cannot be mistaken for credentials by
 * secret scanners.
 */
const TARGET_HASH = "hashofdevicetarget01";
const OTHER_HASH = "hashofdeviceother002";
const MISSING_HASH = "hashofdevicemissing3";

const TARGET_SHARD = TARGET_HASH.slice(0, HASH_SHARD_LEN); // "hash"

const imp: Impression = {
  advertiserId: "adv",
  campaignId: "camp",
  creativeId: "cre",
  ifaHash: TARGET_HASH,
  ifaPresent: true,
  lmt: false,
  appId: "app",
  country: "US",
  ifaType: "rida",
  platform: "roku",
};

/** 2026-09-14T07:30:00Z in unix seconds. */
const T = Date.UTC(2026, 8, 14, 7, 30) / 1000;

describe("rawObjectKey", () => {
  it("puts the hash shard directly after the date so DSAR can prefix-scan one day", () => {
    expect(rawObjectKey(imp, T, "uuid-1")).toBe(
      `dt=2026-09-14/h=${TARGET_SHARD}/hh=07/camp/uuid-1.json`,
    );
  });

  it("keeps the date prefix scannable for analytics", () => {
    expect(rawObjectKey(imp, T, "uuid-1").startsWith("dt=2026-09-14/")).toBe(true);
  });

  it("places the shard before the campaign segment", () => {
    const key = rawObjectKey(imp, T, "u");
    expect(key.indexOf(`h=${TARGET_SHARD}`)).toBeLessThan(key.indexOf("camp"));
  });
});

interface FakeObject {
  key: string;
  customMetadata?: Record<string, string>;
}

/** Minimal R2 list/delete stand-in: enough to exercise paging and prefixing. */
function fakeBucket(
  objects: FakeObject[],
  pageSize = 1000,
  cfg: { dropInclude?: boolean } = {},
) {
  const deleted: string[] = [];
  const listedPrefixes: string[] = [];
  return {
    deleted,
    listedPrefixes,
    bucket: {
      async list(
        opts: { prefix?: string; cursor?: string; limit?: number; include?: string[] } = {},
      ) {
        if (opts.prefix) listedPrefixes.push(opts.prefix);
        // R2 only returns customMetadata when `include` asks for it, so a
        // request that forgets the option looks exactly like an object whose
        // metadata is missing. `dropInclude` forces that behaviour.
        const wantsMetadata =
          (cfg.dropInclude ? false : opts.include?.includes("customMetadata")) ?? false;
        const matching = objects.filter(
          (o) => !opts.prefix || o.key.startsWith(opts.prefix),
        );
        const start = opts.cursor ? Number(opts.cursor) : 0;
        const limit = Math.min(opts.limit ?? 1000, pageSize);
        const slice = matching.slice(start, start + limit);
        const next = start + limit;
        const truncated = next < matching.length;
        return {
          objects: slice.map((o) => ({
            key: o.key,
            customMetadata: wantsMetadata ? o.customMetadata : undefined,
          })),
          truncated,
          cursor: truncated ? String(next) : undefined,
        };
      },
      async delete(keys: string | string[]) {
        deleted.push(...(Array.isArray(keys) ? keys : [keys]));
      },
    },
  };
}

describe("eraseRawByHash", () => {
  const NOW_MS = Date.UTC(2026, 8, 14, 12);

  const K_A = "dt=2026-09-14/h=hash/hh=01/camp/a.json";
  const K_B = "dt=2026-09-14/h=hash/hh=02/camp/b.json";
  const K_C = "dt=2026-09-14/h=hash/hh=02/camp/c.json";
  const K_D = "dt=2026-09-13/h=hash/hh=23/camp/d.json";
  const K_E = "dt=2026-09-14/h=diff/hh=02/camp/e.json";

  const OBJECTS: FakeObject[] = [
    { key: K_A, customMetadata: { ifaHash: TARGET_HASH } },
    { key: K_B, customMetadata: { ifaHash: TARGET_HASH } },
    { key: K_C, customMetadata: { ifaHash: OTHER_HASH } },
    { key: K_D, customMetadata: { ifaHash: TARGET_HASH } },
    { key: K_E, customMetadata: { ifaHash: TARGET_HASH } },
  ];

  /**
   * Bulk fixtures for the paging tests, generated by the key builder itself so
   * they cannot drift from the writer's layout (`bulkObjects` also keeps this
   * file free of hand-written key-shaped literals, which scanners read as
   * secret assignments).
   */
  const bulkObjects = (n: number): FakeObject[] =>
    Array.from({ length: n }, (_, i) => ({
      key: rawObjectKey(imp, T + i, `row-${i}`),
      customMetadata: { ifaHash: TARGET_HASH },
    }));

  it("deletes every row for this hash across the retention window", async () => {
    const { bucket, deleted } = fakeBucket(OBJECTS);
    const env = { RAW: bucket } as unknown as Env;
    const r = await eraseRawByHash(env, TARGET_HASH, { days: 2, now: NOW_MS });
    expect(r.deleted).toBe(3);
    expect(r.truncated).toBe(false);
    expect(r.daysScanned).toBe(2);
    expect(deleted.sort()).toEqual([K_D, K_A, K_B].sort());
  });

  it("never even lists a shard that cannot hold this hash", async () => {
    const { bucket, deleted, listedPrefixes } = fakeBucket(OBJECTS);
    const env = { RAW: bucket } as unknown as Env;
    await eraseRawByHash(env, TARGET_HASH, { days: 2, now: NOW_MS });
    // K_E carries the target hash but sits under a different shard, which is why
    // the shard is a cheap pre-filter and the metadata check is the real guard.
    expect(deleted.includes(K_E)).toBe(false);
    expect(listedPrefixes.every((p) => p.includes(`/h=${TARGET_SHARD}/`))).toBe(true);
  });

  it("leaves other hashes in the same shard alone", async () => {
    const { bucket, deleted } = fakeBucket(OBJECTS);
    const env = { RAW: bucket } as unknown as Env;
    await eraseRawByHash(env, TARGET_HASH, { days: 2, now: NOW_MS });
    expect(deleted.includes(K_C)).toBe(false);
  });

  it("shares a shard with a sibling hash, proving the shard is not the guard", async () => {
    expect(OTHER_HASH.slice(0, HASH_SHARD_LEN)).toBe(TARGET_SHARD);
  });

  it("reports truncation instead of silently under-deleting", async () => {
    const { bucket } = fakeBucket(bulkObjects(30), 10);
    const env = { RAW: bucket } as unknown as Env;
    const r = await eraseRawByHash(env, TARGET_HASH, {
      days: 1,
      now: NOW_MS,
      maxScan: 20,
    });
    expect(r.truncated).toBe(true);
    expect(r.scanned).toBe(20);
    expect(r.deleted).toBe(20);
  });

  it("completes a multi-page day without truncating", async () => {
    const { bucket } = fakeBucket(bulkObjects(25), 10);
    const env = { RAW: bucket } as unknown as Env;
    const r = await eraseRawByHash(env, TARGET_HASH, { days: 1, now: NOW_MS });
    expect(r.truncated).toBe(false);
    expect(r.deleted).toBe(25);
    expect(r.scanned).toBe(25);
  });

  it("visits only the days requested", async () => {
    const { bucket } = fakeBucket(OBJECTS);
    const env = { RAW: bucket } as unknown as Env;
    expect((await eraseRawByHash(env, TARGET_HASH, { days: 1, now: NOW_MS })).daysScanned).toBe(1);
    expect((await eraseRawByHash(env, TARGET_HASH, { days: 5, now: NOW_MS })).daysScanned).toBe(5);
  });

  it("is a no-op when nothing matches", async () => {
    const { bucket, deleted } = fakeBucket(OBJECTS);
    const env = { RAW: bucket } as unknown as Env;
    const r = await eraseRawByHash(env, MISSING_HASH, { days: 2, now: NOW_MS });
    expect(r.deleted).toBe(0);
    expect(deleted).toEqual([]);
  });

  it("fails loudly when objects carry no customMetadata", async () => {
    // The erasure filter keys on customMetadata.ifaHash. If R2 stops returning
    // it, filtering matches nothing and the DSAR would be reported as complete
    // while the subject's rows are still in the bucket. Refusing to answer is
    // the only safe behaviour.
    const { bucket, deleted } = fakeBucket([
      { key: K_A },
      { key: K_B, customMetadata: { ifaHash: TARGET_HASH } },
    ]);
    const env = { RAW: bucket } as unknown as Env;
    await expect(eraseRawByHash(env, TARGET_HASH, { days: 1, now: NOW_MS })).rejects.toBeInstanceOf(
      RawMetadataMissingError,
    );
    expect(deleted).toEqual([]);
  });

  it("names the offending object in the error", async () => {
    const { bucket } = fakeBucket([{ key: K_B }]);
    const env = { RAW: bucket } as unknown as Env;
    await expect(eraseRawByHash(env, TARGET_HASH, { days: 1, now: NOW_MS })).rejects.toThrow(K_B);
  });

  it("fails loudly when metadata is returned but carries no hash", async () => {
    // `customMetadata: {}` is defined, so a check for `undefined` alone would
    // let the filter comparison come out false, skip the object silently, and
    // report a successful erase while the row is still in the bucket.
    const { bucket, deleted } = fakeBucket([
      { key: K_A, customMetadata: {} },
      { key: K_B, customMetadata: { ifaHash: TARGET_HASH } },
    ]);
    const env = { RAW: bucket } as unknown as Env;
    await expect(
      eraseRawByHash(env, TARGET_HASH, { days: 1, now: NOW_MS }),
    ).rejects.toBeInstanceOf(RawMetadataMissingError);
    expect(deleted).toEqual([]);
  });

  it("fails closed if the listing forgets to request customMetadata", async () => {
    // R2 does not return customMetadata unless `include` asks for it. This is
    // the most likely production regression of the fail-closed guard, so the
    // fake must reproduce R2's real behaviour here rather than always answering.
    const { bucket } = fakeBucket([{ key: K_A, customMetadata: { ifaHash: TARGET_HASH } }], 1000, {
      dropInclude: true,
    });
    const env = { RAW: bucket } as unknown as Env;
    await expect(
      eraseRawByHash(env, TARGET_HASH, { days: 1, now: NOW_MS }),
    ).rejects.toBeInstanceOf(RawMetadataMissingError);
  });
});
